### ISSUE TITLE
openssl 1.0 support broken

### ISSUE THREAD

**Issue by dpisano** [bzed/bzed-letsencrypt#40] opened 2018-08-19 01:22 UTC
It looks like #39 has broken openssl 1.0 support. I had to back out 777dd4d to get it to work again. Some logic needs to be added to [letsencrypt_get_certificate_ocsp.sh.erb
](https://github.com/bzed/bzed-letsencrypt/blob/master/templates/letsencrypt_get_certificate_ocsp.sh.erb) to detect the version of openssl installed.

**Comment by bzed** [comment] 2018-08-19 18:29
"It looks like" is not really a proper bug report. Works for me on a few hundred pre-1.1 machines, so I guess you'll have to debug this properly.

**Comment by dpisano** [comment] 2018-08-20 02:31
I'm using a fresh Debian 8 system with openssl 1.0.1t. To get it to work for me I have to change:
```
openssl ocsp -noverify -issuer "${2}" \
    -cert "${1}" \
    -header Host="${OCSPHOST}" \
-url "${OCSPURL}" -respout "${3}.new"
```
to
```
openssl ocsp -noverify -issuer "${2}" \
    -cert "${1}" \
    -header Host "${OCSPHOST}" \
-url "${OCSPURL}" -respout "${3}.new"
```
in `letsencrypt_get_certificate_ocsp.sh.erb`.

When it is `-header Host="${OCSPHOST}"` I will get no output or errors from openssl and a`hostname.crt.ocsp.new` file is not made. Only when I change it to `-header Host "${OCSPHOST}"` will I get an output and a `hostname.crt.ocsp.new` file is made.

**Comment by bzed** [comment] 2018-08-20 10:07
So the problem is on your puppet master?

**Comment by dpisano** [comment] 2018-08-20 11:24
Yes, it is on my puppet master.

**Comment by bzed** [comment] 2018-10-03 12:17
Fixed in e061dcbe5a5782fec9a0da176824b64abe794f7c

**Closed as completed by bzed** 2018-10-03 12:17 UTC

**Comment by bzed** [comment] 2018-10-03 16:30
with f406d21252d330130a82a57769b736e557ce0b05 the fix is fully there. forgot to add that file :)

**Comment by dpisano** [comment] 2018-10-17 02:05
Thanks. I have confirmed that everything works on my side.
